debug: true
index: "https://www.ghink.net"
server:
  host:
  port: 8000
log:
  file: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true
database:
  host:
  port:
  user:
  name:
  password:
redis:
  host:
  port:
  password:
  db: 0
