debug: true
index: "https://www.ghink.net"
server:
  host:
  port: 8000
log:
  file: "logs/app.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true
database:
  host:
  port:
  user:
  name:
  password:
redis:
  host:
  port:
  password:
  db: 0
