debug: true
server:
  host:
  port: 8000
log:
  file: "logs/app.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true
database:
  host:
  port:
  user:
  name:
  password:
redis:
  host:
  port:
  password:
  db: 0
field:
  a: 0
  b: 1
  c: 2
  d: 3
  e: 4
  f: 5
  g: 6
  h: 7
  i: 8
  j: 9
  k: 10

