index: "https://www.ghink.net"
server:
  host:
  port: 8000
log:
  file:
    all: "logs/app.log"
    err: "logs/err.log"
  maxSize: 5
  maxBackups: 100
  maxAge: 30
  compress: true
database:
  host:
  port:
  user:
  name:
  password:
redis:
  host:
  port:
  password:
  db: 0
